# Generated by Django 6.0.5 on 2026-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='name')),
                ('categoria', models.CharField(choices=[('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('gel', 'Gel'), ('acrilico', 'Acrylic'), ('decoracion', 'Nail Art'), ('spa', 'Hand & Foot Spa'), ('otro', 'Other')], default='manicure', max_length=20, verbose_name='category')),
                ('descripcion', models.TextField(help_text='Short text shown on the public service card.', verbose_name='description')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Price in US dollars.', max_digits=8, verbose_name='price')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text="Only used as a visual reference on the public landing page. The REAL duration of each appointment is set per technician in 'Services per technician'. Leaving 60 works fine.", verbose_name='reference duration (min)')),
                ('icono', models.CharField(blank=True, default='✨', help_text='Decorative emoji or symbol (optional).', max_length=10, verbose_name='icon')),
                ('destacado', models.BooleanField(default=False, help_text='Highlighted on the landing page.', verbose_name='featured')),
                ('activo', models.BooleanField(default=True, help_text='If unchecked, this service is hidden from the public site.', verbose_name='active')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Lower number = appears first.', verbose_name='display order')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
