# Generated by Django 6.0.5 on 2026-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Optional. Shown as caption on hover.', max_length=120, verbose_name='title')),
                ('descripcion', models.CharField(blank=True, help_text='Alt text for accessibility and SEO.', max_length=255, verbose_name='description')),
                ('imagen', models.ImageField(help_text='Recommended: 1080×1080 px, max 5MB.', upload_to='gallery/%Y/%m/', verbose_name='image')),
                ('destacada', models.BooleanField(default=False, help_text='Appears larger in the masonry grid.', verbose_name='featured')),
                ('activa', models.BooleanField(default=True, help_text='If unchecked, hidden from the public gallery.', verbose_name='active')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Lower number = appears first.', verbose_name='display order')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['orden', '-creado'],
            },
        ),
    ]
