# Generated by Django 6.0.5 on 2026-05-09 05:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='full name (private)')),
                ('correo', models.EmailField(max_length=254, verbose_name='email (private)')),
                ('telefono', models.CharField(help_text='U.S. format: +1 (555) 123-4567', max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid U.S. phone number. Example: +1 (555) 123-4567 or 555-123-4567.', regex='^\\+?1?[\\s.\\-]*\\(?\\d{3}\\)?[\\s.\\-]*\\d{3}[\\s.\\-]*\\d{4}$')], verbose_name='phone (private)')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage the salon retains from each service.', max_digits=5, verbose_name='commission (%)')),
                ('nickname', models.SlugField(blank=True, help_text="Unique public identifier (e.g. 'mara-fit'). If left blank, it's generated from the name. This is the ONLY thing clients see — the full name stays private.", max_length=40, null=True, unique=True, verbose_name='public nickname')),
                ('bio', models.TextField(blank=True, help_text='Short optional description shown to clients.', max_length=400, verbose_name='public bio')),
                ('foto', models.ImageField(blank=True, help_text='Optional avatar. Recommended 400×400px square.', null=True, upload_to='technicians/', verbose_name='photo / avatar')),
                ('activa', models.BooleanField(default=True, verbose_name='active')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='date')),
                ('monto_original', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount the client paid for the service.', max_digits=10, verbose_name='service price')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text="Auto-calculated: price minus salon's commission.", max_digits=10, verbose_name='technician earnings')),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tip given by the client (100% goes to the technician).', max_digits=10, verbose_name='tip')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='total received')),
                ('notas', models.TextField(blank=True, verbose_name='notes')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('trabajadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.trabajadora', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'Income Record',
                'verbose_name_plural': 'Income Records',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
