# Generated by Django 6.0.5 on 2026-05-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadora',
            name='worker_password',
            field=models.CharField(blank=True, default='', help_text='Password for worker login. Leave blank to disable portal access.', max_length=100, verbose_name='worker portal password'),
        ),
    ]
