# Generated by Django 6.0.5 on 2026-05-09 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120, verbose_name='client name')),
                ('telefono', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid U.S. phone number. Example: +1 (555) 123-4567 or 555-123-4567.', regex='^\\+?1?[\\s.\\-]*\\(?\\d{3}\\)?[\\s.\\-]*\\d{3}[\\s.\\-]*\\d{4}$')], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('fecha', models.DateField(verbose_name='date')),
                ('hora', models.TimeField(verbose_name='time')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Auto-filled from the (technician, service) pair on save. Editable manually if the admin needs to adjust.', verbose_name='duration (minutes)')),
                ('notas', models.TextField(blank=True, verbose_name='notes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('confirmada', 'Confirmed'), ('completada', 'Completed'), ('cancelada', 'Cancelled')], default='pendiente', max_length=20, verbose_name='status')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.servicio', verbose_name='service')),
                ('trabajadora', models.ForeignKey(blank=True, help_text='If empty, an admin will assign a technician later.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='panel.trabajadora', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['fecha', 'hora'], name='bookings_ci_fecha_932c5e_idx'), models.Index(fields=['trabajadora', 'fecha'], name='bookings_ci_trabaja_b039ed_idx'), models.Index(fields=['fecha', 'estado'], name='bookings_ci_fecha_9765c1_idx'), models.Index(fields=['estado'], name='bookings_ci_estado_37c641_idx')],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('hora_inicio', models.TimeField(verbose_name='start time')),
                ('hora_fin', models.TimeField(verbose_name='end time')),
                ('activo', models.BooleanField(default=True, verbose_name='active')),
                ('trabajadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to='panel.trabajadora', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['trabajadora', 'dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='hora_fin_after_hora_inicio', violation_error_message='End time must be after start time.')],
            },
        ),
        migrations.CreateModel(
            name='TrabajadoraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.PositiveIntegerField(help_text="Time THIS technician takes for THIS service. Overrides the service's reference duration.", validators=[django.core.validators.MinValueValidator(5)], verbose_name='duration (minutes)')),
                ('activo', models.BooleanField(default=True, help_text='Uncheck if the technician temporarily stops offering this service.', verbose_name='active')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadoras_que_lo_realizan', to='core.servicio', verbose_name='service')),
                ('trabajadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_que_realiza', to='panel.trabajadora', verbose_name='technician')),
            ],
            options={
                'verbose_name': 'Service per Technician',
                'verbose_name_plural': 'Services per Technician',
                'ordering': ['trabajadora', 'servicio'],
                'constraints': [models.UniqueConstraint(fields=('trabajadora', 'servicio'), name='unique_trabajadora_servicio', violation_error_message='This technician already has that service assigned.')],
            },
        ),
    ]
